spring:
  datasource:
    url: jdbc:mysql://mysql:3306/show_tick?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  data:
    redis:
      host: redis # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      timeout: 300ms # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info

logstash:
  host: logstash