spring:
  application:
    name: showtick-admin
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

redis:
  database: showtick
  key:
    user: 'admin'
  expire:
    common: 86400 # 24hours

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: showTick-admin
  expiration: 86400000
  tokenHead: 'Bearer '

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /v3/api-docs/*
      - /*/*.html
      - /*/*.js
      - /*/*.css
      - /*/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /users/sso/**
      - /admin/**
